package defpackage;

/* compiled from: PG */
/* renamed from: cig  reason: default package */
/* loaded from: classes.dex */
public final class cig {
    private static final cio A;
    private static final cio B;
    private static final cio C;
    private static final cio D;
    private static final cio E;
    private static final cio F;
    private static final cio G;
    public static final ciq a;
    public static final ciq b;
    public static final ciq c;
    public static final ciq d;
    public static final ciq e;
    public static final ciq f;
    public static final ciq g;
    public static final cio h;
    public static final cio i;
    public static final cio j;
    public static final cio k;
    public static final cio l;
    public static final cio m;
    public static final cio n;
    public static final cio o;
    public static final cio p;
    public static final cio q;
    public static final cio r;
    public static final cio s;
    public static final cio t;
    public static final cio u;
    public static final cio v;
    private static final ciq w;
    private static final ciq x;
    private static final ciq y;
    private static final cio z;

    static {
        cip cipVar = new cip();
        cipVar.a = "camcorder.bitrate";
        a = cipVar.a();
        cip cipVar2 = new cip();
        cipVar2.a = "camcorder.capture_rate";
        cipVar2.c = psl.a(30, 60, 120, 240);
        b = cipVar2.a();
        cip cipVar3 = new cip();
        cipVar3.a = "detect_face_on_front_camera";
        h = cipVar3.i();
        cip cipVar4 = new cip();
        cipVar4.a = "detect_face_on_non_front_camera";
        i = cipVar4.i();
        cip cipVar5 = new cip();
        cipVar5.a = "camcorder.fs";
        z = cipVar5.g();
        cip cipVar6 = new cip();
        cipVar6.a = "camcorder_slowmo.fs";
        A = cipVar6.g();
        cip cipVar7 = new cip();
        cipVar7.a = "camcorder.h265";
        cipVar7.f();
        cip cipVar8 = new cip();
        cipVar8.a = "enable_hevc_setting";
        j = cipVar8.h();
        cip cipVar9 = new cip();
        cipVar9.a = "camcorder.codec";
        k = cipVar9.e();
        cip cipVar10 = new cip();
        cipVar10.a = "camcorder.codec_sm";
        l = cipVar10.h();
        cip cipVar11 = new cip();
        cipVar11.a = "camcorder.no_audio";
        cipVar11.f();
        cip cipVar12 = new cip();
        cipVar12.a = "camcorder.ois";
        m = cipVar12.e();
        cip cipVar13 = new cip();
        cipVar13.a = "camcorder.stereo";
        n = cipVar13.e();
        cip cipVar14 = new cip();
        cipVar14.a = "camcorder.sf_share";
        cipVar14.f();
        cip cipVar15 = new cip();
        cipVar15.a = "camcorder.trk_yuv";
        B = cipVar15.g();
        cip cipVar16 = new cip();
        cipVar16.a = "camcorder.cam_contlr";
        C = cipVar16.g();
        cip cipVar17 = new cip();
        cipVar17.a = "camcorder.viewfinder_effect";
        cipVar17.f();
        cip cipVar18 = new cip();
        cipVar18.a = "fps_video_setting_writeable";
        o = cipVar18.i();
        cip cipVar19 = new cip();
        cipVar19.a = "google_llv_30_fps_non_4k";
        p = cipVar19.i();
        cip cipVar20 = new cip();
        cipVar20.a = "google_llv_auto_fps_non_4k";
        q = cipVar20.i();
        cip cipVar21 = new cip();
        cipVar21.a = "max_1080p_torch_video_duration_seconds";
        w = cipVar21.a();
        cip cipVar22 = new cip();
        cipVar22.a = "max_1080p_video_duration_seconds";
        c = cipVar22.a();
        cip cipVar23 = new cip();
        cipVar23.a = "max_2160p_torch_video_duration_seconds";
        x = cipVar23.a();
        cip cipVar24 = new cip();
        cipVar24.a = "max_2160p_video_duration_seconds";
        d = cipVar24.a();
        cip cipVar25 = new cip();
        cipVar25.a = "max_hfr_torch_video_duration_seconds";
        y = cipVar25.a();
        cip cipVar26 = new cip();
        cipVar26.a = "max_hfr_video_duration_seconds";
        e = cipVar26.a();
        cip cipVar27 = new cip();
        cipVar27.a = "torch_1080p_video_enabled";
        D = cipVar27.h();
        cip cipVar28 = new cip();
        cipVar28.a = "torch_2160p_video_enabled";
        E = cipVar28.h();
        cip cipVar29 = new cip();
        cipVar29.a = "torch_hfr_video_enabled";
        F = cipVar29.h();
        cip cipVar30 = new cip();
        cipVar30.a = "UNLOCK_AF_AE_WITH_SCENE_CHANGE_FOR_FRONT_CAM";
        r = cipVar30.i();
        cip cipVar31 = new cip();
        cipVar31.a = "camcorder.vidqual_front";
        cipVar31.c = psl.a(144, 240, 288, 480, 720, 1080, 2160);
        f = cipVar31.a();
        cip cipVar32 = new cip();
        cipVar32.a = "camcorder.vidqual_back";
        cipVar32.c = psl.a(144, 240, 288, 480, 720, 1080, 2160);
        g = cipVar32.a();
        cip cipVar33 = new cip();
        cipVar33.a = "zoom_override_enabled";
        s = cipVar33.i();
        cip cipVar34 = new cip();
        cipVar34.a = "camcorder.max_zoom_30fps";
        t = cipVar34.k();
        cip cipVar35 = new cip();
        cipVar35.a = "camcorder.max_zoom_default";
        u = cipVar35.k();
        cip cipVar36 = new cip();
        cipVar36.a = "camcorder_prewire_record_surface";
        G = cipVar36.h();
        cip cipVar37 = new cip();
        cipVar37.a = "camcorder_recorder_warm_up";
        v = cipVar37.h();
    }

    public static void a(cis cisVar, ncz nczVar) {
        cisVar.b(a, (Integer) null);
        cisVar.b(b, (Integer) null);
        cisVar.c(h, true);
        cisVar.c(i, true);
        cisVar.i(z);
        cisVar.i(A);
        cisVar.b(j, true);
        cisVar.a(k, nczVar.e);
        cisVar.b(l, false);
        cisVar.a(m, true);
        cisVar.a(n, nczVar.e);
        cisVar.i(B);
        cisVar.i(C);
        cisVar.c(o, true);
        cisVar.b(w, 0);
        cisVar.b(c, 0);
        cisVar.b(x, 0);
        cisVar.b(d, 0);
        cisVar.b(y, 0);
        cisVar.b(e, 0);
        cisVar.c(p, true);
        cisVar.c(q, true);
        cisVar.b(D, true);
        cisVar.b(E, true);
        cisVar.b(F, true);
        cisVar.c(r, false);
        cisVar.b(f, (Integer) null);
        cisVar.b(g, (Integer) null);
        cisVar.c(s, true);
        cisVar.a(t, 5.0f);
        cisVar.a(u, 3.0f);
        cisVar.b(G, false);
        cisVar.b(v, false);
    }
}